apiVersion: v1
kind: Service
metadata:
  name: train-ticket-service
  namespace: train-ticket
spec:
  type: LoadBalancer
  selector:
    app: train-ticket
  ports:
    - port: 80
      targetPort: 8080
